apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: test
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 600m
    defaultRequest:
      memory: 256Mi
      cpu: 300m
    max:
      memory: 2000Mi
      cpu: 1000m
    min:
      memory: 128Mi
      cpu: 200m
    type: Container
